/** Section 3 — Values & Instincts. Source: docs/content/brand-dna/section-3-values-instincts.md */
import { q, type Question } from "./types";

export const SECTION_3: Question[] = [
  q("s3_q01", 3, "shared",
    { founder: "You have to make a call that could go either way. Nobody's watching. What do you rely on?", business: "The business faces a decision that could go either way. What does it rely on?" },
    ["Your gut. If you had to explain why, you couldn't \u2014 but you trust it.", ["gut_first", "risk_appetite", "independence"]],
    ["The data. Not because you don't have instincts \u2014 because you don't trust them alone.", ["head_first", "risk_caution", "prudence"]],
    ["Past experience. You've been here before, or close enough.", ["patience", "resilience", "conscientiousness"]],
    ["Someone you trust. Not for the answer \u2014 for the question you haven't asked yourself.", ["curiosity", "listen_first", "affiliation"]]),

  q("s3_q02", 3, "shared",
    { founder: "What's most likely to keep you up at 2am?", business: "What's the thing that keeps the leadership up at night?" },
    ["Something you said that you can't take back.", ["neuroticism", "high_sensitivity", "tonal_awareness"]],
    ["A decision you're not sure was right.", ["prudence", "perfectionism", "neuroticism"]],
    ["Nothing. Once a day's over, it's over.", ["thick_skin", "resilience", "pragmatism"]],
    ["The thing you should have done and didn't.", ["conscientiousness", "neuroticism", "conviction"]]),

  q("s3_q03", 3, "shared", "You discover someone has copied your work \u2014 almost exactly. What's your first feeling?",
    ["Anger. That took effort and they took a shortcut.", ["conviction", "confrontation_comfort", "admires_craft"]],
    ["Flattery, briefly. Then irritation.", ["thick_skin", "pragmatism"]],
    ["You move. If they can copy it, it wasn't far enough ahead.", ["innovation_pull", "ambition", "resilience"]],
    ["You say nothing. You know who did the work. That's enough.", ["quiet_confidence", "independence", "patience"]]),

  q("s3_q04", 3, "shared",
    { founder: "You lose a client you thought was solid. What's the first thing you do?", business: "The brand loses a client that seemed committed. What's the response?" },
    ["Ask them why. Not to win them back \u2014 to understand.", ["curiosity", "listen_first", "resilience"]],
    ["Review what you did. If it's your fault, own it. If it isn't, move on.", ["head_first", "transparency", "pragmatism"]],
    ["Feel it. Then put it somewhere useful.", ["high_sensitivity", "resilience", "gut_first"]],
    ["Replace them. Dwelling doesn't pay the bills.", ["thick_skin", "ambition", "pragmatism"]]),

  q("s3_q05", 3, "shared", "Someone offers you a lot of money for work that compromises what you believe in. How quickly do you say no?",
    ["Immediately. There's no amount that's worth your integrity.", ["conviction", "authenticity", "independence"]],
    ["You hear them out. Maybe there's a version that works for both of you.", ["pragmatism", "agreeableness", "openness"]],
    ["You think about it longer than you'd like to admit.", ["neuroticism", "prudence", "transparency"]],
    ["You never get offered that deal, because people already know where you stand.", ["reputation_weight", "conviction", "quiet_confidence"]]),

  q("s3_q06", 3, "shared",
    { founder: "How involved are you in the details of your own business?", business: "How involved is leadership in the details?" },
    ["Very. If you're not across it, who is?", ["control_need", "conscientiousness", "perfectionism"]],
    ["Selectively. You go deep on what matters and let the rest go.", ["pragmatism", "curation_instinct", "head_first"]],
    ["Less than you should be. But you trust the people you've put in place.", ["loyalty", "agreeableness", "risk_appetite"]],
    ["You oscillate. Some weeks you're in everything, others you can't look.", ["neuroticism", "gut_first", "improviser"]]),

  q("s3_q07", 3, "shared", "Which of these is closest to the truth?",
    ["You take risks other people don't see as risks \u2014 because you've done the thinking.", ["risk_appetite", "head_first", "conviction"]],
    ["You're more cautious than you appear. People assume you're braver than you are.", ["risk_caution", "selective_vulnerability", "introversion"]],
    ["You take risks, then worry about them. Both things are true at the same time.", ["neuroticism", "risk_appetite", "gut_first"]],
    ["You don't think in terms of risk. You think in terms of cost of not doing it.", ["ambition", "pragmatism", "proving_ground"]]),

  q("s3_q08", 3, "shared", "What makes you lose patience the fastest?",
    ["Dishonesty. Even small dishonesty.", ["authenticity", "transparency", "conviction"]],
    ["Indecision. Make a call. Adjust if it's wrong. But move.", ["pragmatism", "risk_appetite", "directness"]],
    ["Laziness disguised as busy-ness. Doing things is not the same as doing the right things.", ["conscientiousness", "admires_craft", "independence"]],
    ["People not saying what they actually mean.", ["directness", "confrontation_comfort", "high_sensitivity"]]),

  q("s3_q09", 3, "shared", "Someone who was loyal to you makes a mistake that costs you. What happens?",
    ["You absorb it. Loyalty has a longer memory than one bad day.", ["loyalty", "patience", "resilience"]],
    ["You're honest about the impact. Then you figure out what happened.", ["transparency", "confrontation_comfort", "head_first"]],
    ["It changes something. You can't help it \u2014 trust doesn't fully reset.", ["prudence", "high_sensitivity", "neuroticism"]],
    ["Depends on the mistake. Carelessness is different from bad luck.", ["head_first", "pragmatism", "independence"]]),

  q("s3_q10", 3, "shared",
    { founder: "You're about to make a big decision and everyone around you disagrees. What do you do?", business: "The business is about to make a big call and the market disagrees. What happens?" },
    ["Go anyway. You've been right when they were wrong before.", ["conviction", "independence", "risk_appetite"]],
    ["Slow down. If everyone sees something you don't, at least understand what it is.", ["prudence", "curiosity", "listen_first"]],
    ["Go, but quietly. No need to make it a confrontation.", ["quiet_confidence", "independence", "conflict_avoidant"]],
    ["Feel the doubt \u2014 then decide whether the doubt is information or just fear.", ["gut_first", "high_sensitivity", "resilience"]]),

  q("s3_q11", 3, "founder", "What are you actually building? Not the product or service \u2014 the thing underneath.",
    ["Something I can be proud of. That's the real metric.", ["legacy_drive", "authenticity", "admires_craft"]],
    ["Freedom. The kind where nobody can tell me what to do next.", ["independence", "power_drive", "proving_ground"]],
    ["Proof. That this way of doing things actually works.", ["proving_ground", "conviction", "ambition"]],
    ["A life. The business is the vehicle, not the destination.", ["pragmatism", "patience", "openness"]]),

  q("s3_q12", 3, "shared", "Someone praises your work publicly. What's your honest internal response?",
    ["Uncomfortable, but you manage it gracefully.", ["introversion", "selective_vulnerability", "tonal_awareness"]],
    ["Energised. Recognition fuels you more than you'd like to admit.", ["extraversion", "achievement_orientation", "reputation_weight"]],
    ["Suspicious. You wonder what they want.", ["prudence", "independence", "thick_skin"]],
    ["Grateful, briefly. Then you think about whether it was actually that good.", ["neuroticism", "perfectionism", "high_sensitivity"]]),

  q("s3_q13", 3, "founder", "If you had to name your worst quality as a business owner, what's closest?",
    ["You hold on too long. To people, to ideas, to things that aren't working.", ["loyalty", "patience", "conflict_avoidant"]],
    ["You set a bar most people can't clear. Including yourself.", ["perfectionism", "control_need", "conscientiousness"]],
    ["You move too fast. You've broken things that didn't need breaking.", ["risk_appetite", "ambition", "improviser"]],
    ["You carry things that aren't yours to carry.", ["high_sensitivity", "neuroticism", "agreeableness"]]),

  q("s3_q14", 3, "shared", "When everything goes wrong at once, what happens to you?",
    ["You get calmer. The worse it gets, the steadier you are.", ["resilience", "thick_skin", "head_first"]],
    ["You get sharper. Crisis strips out everything except what matters.", ["resilience", "pragmatism", "directness"]],
    ["You feel it \u2014 all of it \u2014 but you keep moving.", ["high_sensitivity", "resilience", "gut_first"]],
    ["You freeze, briefly. Then you make a list.", ["neuroticism", "conscientiousness", "head_first"]]),

  q("s3_q15", 3, "shared", "A colleague, client, or partner needs something from you at the worst possible time. What do you do?",
    ["Help. Always. The inconvenience is your problem, not theirs.", ["loyalty", "agreeableness", "warmth_in_voice"]],
    ["Help if it's real. Assess first \u2014 not everything urgent is actually urgent.", ["pragmatism", "head_first", "prudence"]],
    ["Help, but resent it slightly. And feel guilty about the resentment.", ["agreeableness", "neuroticism", "high_sensitivity"]],
    ["Be honest about your capacity. Say what you can do and what you can't.", ["directness", "transparency", "independence"]]),

  q("s3_q16", 3, "shared",
    { founder: "What's the thing in your work you will never compromise on \u2014 even when it costs you?", business: "What does the brand refuse to compromise on, even when it's expensive?" },
    ["Quality. The output has to be right or it doesn't go out.", ["perfectionism", "admires_craft", "conscientiousness"]],
    ["Honesty. Even when the honest thing is harder to sell.", ["authenticity", "transparency", "confrontation_comfort"]],
    ["How people are treated. The work isn't worth it if it comes at someone's expense.", ["agreeableness", "loyalty", "warmth_in_voice"]],
    ["The way it's done. Process matters, not just outcomes.", ["conscientiousness", "admires_craft", "control_need"]]),

  q("s3_q17", 3, "shared",
    { founder: "Where are you in ten years? Not what you're doing \u2014 how you feel.", business: "Where is the brand in ten years? Not what it does \u2014 how it feels." },
    ["Settled. Respected. Still doing the work, but with less to prove.", ["legacy_drive", "patience", "quiet_confidence"]],
    ["Bigger. Not because you chased it \u2014 because the work demanded it.", ["ambition", "achievement_orientation", "pragmatism"]],
    ["Free. From obligation, from compromise, from doing things the wrong way.", ["independence", "proving_ground", "power_drive"]],
    ["The same, but better at it. You don't need a different life \u2014 just a deeper one.", ["patience", "authenticity", "openness"]]),

  q("s3_q18", 3, "founder", "There's a version of you that only exists when you're alone with your work. What's that version like?",
    ["Calmer. Slower. More careful than the version people know.", ["introversion", "conscientiousness", "patience"]],
    ["Harder on yourself than anyone else would be.", ["perfectionism", "neuroticism", "high_sensitivity"]],
    ["More uncertain than you let on. But you keep that useful.", ["selective_vulnerability", "neuroticism", "resilience"]],
    ["Exactly the same. There's no private version.", ["authenticity", "extraversion", "transparency"]]),

  q("s3_q19", 3, "business", "The market rewards something your brand doesn't believe in. How long before you feel the pressure?",
    ["You don't. What the market rewards is the market's problem.", ["conviction", "independence", "thick_skin"]],
    ["Immediately. But you hold. The pressure is information, not instruction.", ["resilience", "prudence", "conviction"]],
    ["You'd consider whether you're wrong. Maybe the market knows something you don't.", ["openness", "curiosity", "agreeableness"]],
    ["You feel it daily. It's exhausting being the one who holds the line.", ["neuroticism", "conviction", "proving_ground"]]),

  q("s3_q20", 3, "business", "How much does the brand trust the people inside it?",
    ["Fully. Hire right, then get out of the way.", ["loyalty", "risk_appetite", "openness"]],
    ["Mostly. Trust but verify \u2014 some things need oversight.", ["control_need", "prudence", "conscientiousness"]],
    ["It's earned. New people prove themselves before the brand leans on them.", ["prudence", "independence", "patience"]],
    ["The brand has been burned. Trust is harder than it used to be.", ["risk_caution", "neuroticism", "resilience"]]),
];
