/** Section 5 — Brand Aspiration. Source: docs/content/brand-dna/section-5-brand-aspiration.md */
import { q, type Question } from "./types";

export const SECTION_5: Question[] = [
  q("s5_q01", 5, "shared",
    { founder: "If people in your industry talk about you in five years, what do you want them to say?", business: "If people in the industry talk about the brand in five years, what should they say?" },
    ["\u201cThey're the best at what they do. Nobody's close.\u201d", ["premium_positioning", "admires_craft", "ambition"]],
    ["\u201cThey did it their own way. And it worked.\u201d", ["underdog_energy", "independence", "proving_ground"]],
    ["\u201cThey actually care. About the work, about people, about getting it right.\u201d", ["authenticity", "warmth_in_voice", "loyalty"]],
    ["\u201cI'm not sure how to describe them. But you'd know them if you saw them.\u201d", ["category_creation", "quiet_confidence", "curation_instinct"]]),

  q("s5_q02", 5, "shared",
    { founder: "A direct competitor is getting a lot of attention. What's your honest reaction?", business: "A competitor is getting significant market attention. What's the real response?" },
    ["Good for them. Your race is with yourself.", ["quiet_confidence", "patience", "independence"]],
    ["You study what they're doing right. Then do something better.", ["ambition", "achievement_orientation", "head_first"]],
    ["It burns. You know you should be above it, but competition fuels you.", ["proving_ground", "reputation_weight", "neuroticism"]],
    ["You ignore it. Attention is not the same as quality.", ["rejects_trend", "conviction", "thick_skin"]]),

  q("s5_q03", 5, "shared",
    { founder: "In a perfect world, how big is your business?", business: "In a perfect world, how big is this brand?" },
    ["Small and excellent. Ten people who are the best at what they do.", ["premium_positioning", "admires_craft", "local_roots"]],
    ["Big enough to matter. You want influence, not just income.", ["power_drive", "ambition", "global_ambition"]],
    ["Big enough that you don't have to worry anymore. Then you stop.", ["pragmatism", "independence", "patience"]],
    ["The size doesn't matter. The work matters. The size is just a side effect.", ["quiet_confidence", "authenticity", "legacy_drive"]]),

  q("s5_q04", 5, "shared",
    { founder: "Would you rather build a community around your work, or let the work speak for itself?", business: "Should the brand build a community, or let the work speak?" },
    ["Community. The people who care about what you do ARE the brand.", ["community_building", "affiliation", "warmth_in_voice"]],
    ["The work. Build something undeniable and the right people will find it.", ["quiet_confidence", "admires_craft", "introversion"]],
    ["Both, but differently. You want a following, not a crowd.", ["curation_instinct", "thought_leadership", "selective_vulnerability"]],
    ["Neither. Just clients who value what you do. A community sounds exhausting.", ["introversion", "pragmatism", "independence"]]),

  q("s5_q05", 5, "shared",
    { founder: "What's the gap between how your business looks right now and how you want it to feel?", business: "What's the gap between the brand today and the brand you're building toward?" },
    ["It needs to feel more premium. The quality is there \u2014 the presentation isn't yet.", ["premium_positioning", "admires_craft", "ambition"]],
    ["It needs to feel more human. Right now it's too polished, too careful.", ["warmth_in_voice", "anti_polish", "personality_forward"]],
    ["It needs to feel more confident. Less explaining, more showing.", ["quiet_confidence", "brevity", "proving_ground"]],
    ["There isn't one. It already feels like us \u2014 it just needs more reach.", ["authenticity", "global_ambition", "patience"]]),

  q("s5_q06", 5, "shared",
    { founder: "If you could be the first name people think of for one thing, what is it?", business: "If the brand could own one association in people's minds, what is it?" },
    ["Quality. \u201cIf you want it done right, go to them.\u201d", ["premium_positioning", "admires_craft", "legacy_drive"]],
    ["Originality. \u201cNobody else does what they do.\u201d", ["category_creation", "innovation_pull", "independence"]],
    ["Trust. \u201cThey'll tell you the truth, even when it's not what you want to hear.\u201d", ["authenticity", "confrontation_comfort", "transparency"]],
    ["Feeling. \u201cThere's something about them. You can't quite explain it.\u201d", ["emotional_resonance", "quiet_confidence", "warmth"]]),

  q("s5_q07", 5, "shared",
    { founder: "Which matters more for you?", business: "Which matters more for the brand?" },
    ["Being respected. You want authority \u2014 not approachability at the cost of substance.", ["thought_leadership", "premium_positioning", "power_drive"]],
    ["Being liked. Genuine warmth opens more doors than expertise alone.", ["warmth_in_voice", "affiliation", "agreeableness"]],
    ["Being trusted. Not liked or respected \u2014 just trusted.", ["authenticity", "quiet_confidence", "loyalty"]],
    ["Being remembered. You'd rather be distinctive than universally approved.", ["category_creation", "underdog_energy", "taste_as_identity"]]),

  q("s5_q08", 5, "shared",
    { founder: "Your instinct on pricing:", business: "The brand's instinct on pricing:" },
    ["Premium. If you're the best, charge like it. The right clients will come.", ["premium_positioning", "conviction", "ambition"]],
    ["Fair. You want to be accessible without devaluing the work.", ["warmth_in_voice", "agreeableness", "pragmatism"]],
    ["Don't compete on price. Ever. Compete on something they can't copy.", ["category_creation", "independence", "rejects_trend"]],
    ["Honestly? You're still figuring this out.", ["transparency", "openness", "neuroticism"]]),

  q("s5_q09", 5, "founder", "Be honest. Which of these drives you most?",
    ["Proving that your way works. Against the doubters, the skeptics, the conventional.", ["proving_ground", "conviction", "underdog_energy"]],
    ["Building something you can hand off or hand down. Something that lasts.", ["legacy_drive", "patience", "systems_forward"]],
    ["Being the best at what you do. Not famous \u2014 just undeniably the best.", ["achievement_orientation", "admires_craft", "premium_positioning"]],
    ["Freedom. Financial, creative, logistical \u2014 the ability to say yes and no on your own terms.", ["independence", "power_drive", "pragmatism"]]),

  q("s5_q10", 5, "shared", "Which kind of success matters more to you?",
    ["The kind other people can see. Recognition validates the work.", ["reputation_weight", "extraversion", "achievement_orientation"]],
    ["The kind you feel internally. You know when it's good. That's enough.", ["introversion", "quiet_confidence", "authenticity"]],
    ["The kind that compounds. Each success makes the next one easier.", ["ambition", "patience", "achievement_orientation"]],
    ["The kind that surprised you. You didn't expect this, and that makes it better.", ["openness", "gut_first", "improviser"]]),

  q("s5_q11", 5, "shared",
    { founder: "How important is where you're based?", business: "How important is geography to the brand?" },
    ["Central. This place is part of who you are and what you make.", ["local_roots", "warmth", "sensory_memory"]],
    ["Useful, not essential. You work from here, but you think beyond here.", ["pragmatism", "global_ambition"]],
    ["Irrelevant. The internet made geography optional. You're building for everywhere.", ["global_ambition", "innovation_pull", "systems_forward"]],
    ["It matters to other people more than it matters to you. But you use that.", ["tonal_awareness", "pragmatism", "reputation_weight"]]),

  q("s5_q12", 5, "shared",
    { founder: "How visible should you be in your own marketing?", business: "How visible should the founder/leadership be in the brand's marketing?" },
    ["Very. The person IS the brand. People connect with people, not logos.", ["personality_forward", "extraversion", "warmth_in_voice"]],
    ["Present but not centred. The work should lead, with the person behind it.", ["quiet_confidence", "admires_craft", "introversion"]],
    ["As little as possible. Build a brand that doesn't depend on one person.", ["systems_forward", "pragmatism", "legacy_drive"]],
    ["Strategically. Show up for the right moments. Disappear for the rest.", ["selective_vulnerability", "curation_instinct", "tonal_awareness"]]),

  q("s5_q13", 5, "shared",
    { founder: "What would you sacrifice for the business if you had to?", business: "What would the brand sacrifice if it had to choose?" },
    ["Speed. You'd rather be slow and right than fast and wrong.", ["patience", "perfectionism", "admires_craft"]],
    ["Size. You'd stay small forever if it meant keeping the quality.", ["premium_positioning", "independence", "local_roots"]],
    ["Comfort. You'd do the hard thing, the unpopular thing, if it was honest.", ["conviction", "confrontation_comfort", "proving_ground"]],
    ["Control. You'd let the right people take the wheel if the work got better.", ["pragmatism", "loyalty", "openness"]]),

  q("s5_q14", 5, "shared",
    { founder: "What do you want to have built when you're done?", business: "When people look back at this brand, what should they see?" },
    ["Something that lasted. Not a moment \u2014 a body of work.", ["legacy_drive", "patience", "admires_craft"]],
    ["Something that changed how people think about this industry.", ["category_creation", "thought_leadership", "ambition"]],
    ["Something that helped real people. Not at scale \u2014 one at a time.", ["warmth_in_voice", "community_building", "loyalty"]],
    ["Something that was unmistakably yours. A fingerprint, not a template.", ["personality_forward", "taste_as_identity", "independence"]]),

  q("s5_q15", 5, "business", "If a stranger experienced the brand once and described it to a friend, what's the one word you'd want them to use?",
    ["Premium.", ["premium_positioning", "admires_craft"]],
    ["Real.", ["authenticity", "warmth_in_voice", "anti_polish"]],
    ["Different.", ["category_creation", "innovation_pull", "underdog_energy"]],
    ["Trusted.", ["quiet_confidence", "loyalty", "transparency"]]),

  q("s5_q16", 5, "shared", "Which growth philosophy is closest to yours?",
    ["Slow and deep. Go further with fewer, not wider with more.", ["patience", "premium_positioning", "local_roots"]],
    ["Ambitious but deliberate. Big goals, careful steps.", ["ambition", "prudence", "achievement_orientation"]],
    ["Organic. Let the work attract the opportunities. No forcing.", ["quiet_confidence", "patience", "openness"]],
    ["Fast. Move, learn, adjust. The market doesn't wait.", ["risk_appetite", "ambition", "pragmatism"]]),

  q("s5_q17", 5, "shared",
    { founder: "What kind of power matters most to you?", business: "What kind of influence matters most to the brand?" },
    ["The power to say no. To bad work, bad clients, bad compromises.", ["independence", "conviction", "power_drive"]],
    ["The power to shape how people see your industry.", ["thought_leadership", "power_drive", "category_creation"]],
    ["The power to help. To open doors for people who remind you of yourself.", ["affiliation", "warmth_in_voice", "legacy_drive"]],
    ["The power to not need anyone else's permission.", ["independence", "power_drive", "proving_ground"]]),

  q("s5_q18", 5, "shared",
    { founder: "Last one. The version of your business that lives in your head \u2014 the one you haven't built yet \u2014 what's it like?", business: "Last one. The version of this brand that lives in leadership's head \u2014 the one not built yet \u2014 what's it like?" },
    ["Effortless. The quality is so consistent that it doesn't need to be explained.", ["premium_positioning", "admires_craft", "quiet_confidence"]],
    ["Magnetic. People come to it because they want to be part of something real.", ["community_building", "personality_forward", "warmth"]],
    ["Undeniable. Nobody questions whether it belongs. It defined the category.", ["category_creation", "proving_ground", "legacy_drive"]],
    ["Quiet. It does exceptional work for people who get it. And that's enough.", ["quiet_confidence", "admires_restraint", "independence"]]),

  q("s5_q19", 5, "business", "What does the brand owe its customers?",
    ["The best possible version of what was promised. Every time.", ["admires_craft", "conscientiousness", "premium_positioning"]],
    ["Honesty. Even when it's uncomfortable.", ["authenticity", "transparency", "confrontation_comfort"]],
    ["A feeling. Something they didn't know they needed.", ["emotional_resonance", "warmth", "personality_forward"]],
    ["Nothing except the work. Good work is the relationship.", ["independence", "pragmatism", "quiet_confidence"]]),

  q("s5_q20", 5, "founder", "What would make you walk away from this business?",
    ["If it stopped being about the work and became about the money.", ["authenticity", "admires_craft", "legacy_drive"]],
    ["If it started requiring you to be someone you're not.", ["independence", "authenticity", "proving_ground"]],
    ["If the people around you stopped caring as much as you do.", ["loyalty", "perfectionism", "high_sensitivity"]],
    ["Nothing. This is what you're doing. There's no plan B.", ["conviction", "ambition", "resilience"]]),
];
