/** Section 1 — Aesthetic Identity. Source: docs/content/brand-dna/section-1-aesthetic-identity.md */
import { q, type Question } from "./types";

export const SECTION_1: Question[] = [
  q("s1_q01", 1, "shared", "Pick the room you'd work in if nobody could see it.",
    ["White walls, one good lamp, nothing extra.", ["minimalism", "geometric_precision"]],
    ["Books everywhere, warm light, a record playing.", ["warmth", "analogue_texture", "sensory_memory"]],
    ["Concrete floors, big windows, one striking piece on the wall.", ["high_contrast", "cinematic_eye"]],
    ["Soft textures, warm colours, things you've collected from everywhere.", ["organic_forms", "maximalism", "tactile_craft"]]),

  q("s1_q02", 1, "shared",
    { founder: "Someone hands you a blank canvas and says \u201cmake something.\u201d What's your first instinct?", business: "Someone hands your team a blank canvas and says \u201cmake something.\u201d What's the first instinct?" },
    ["Leave most of it empty. The space is the point.", ["minimalism", "admires_restraint"]],
    ["Fill it with texture \u2014 layers, edges, something you can feel.", ["maximalism", "tactile_craft", "anti_polish"]],
    ["One bold mark. Let it sit there.", ["high_contrast", "quiet_confidence"]],
    ["Something that tells a story if you look long enough.", ["cinematic_eye", "visual_storytelling"]]),

  q("s1_q03", 1, "shared",
    { founder: "You're choosing the photography style for your next project. What feels right?", business: "You're choosing the photography style for the brand's next campaign. What feels right?" },
    ["Clean, bright, lots of white. Every element in the frame on purpose.", ["minimalism", "geometric_precision", "conscientiousness"]],
    ["Natural light, warm tones, a bit of grain. Like a memory of a good day.", ["warmth", "analogue_texture", "sensory_memory"]],
    ["Dramatic. Strong shadows, one subject, the rest falls away.", ["high_contrast", "cinematic_eye"]],
    ["Textured and raw. Imperfect on purpose. You can almost touch it.", ["organic_forms", "tactile_craft", "anti_polish"]]),

  q("s1_q04", 1, "shared",
    { founder: "Which colour palette would you trust to represent you?", business: "Which colour palette would you trust to represent the brand?" },
    ["Warm earth \u2014 terracotta, sage, cream, clay.", ["warmth", "muted_palette", "organic_forms"]],
    ["Monochrome with one accent \u2014 black, white, grey, one sharp red.", ["high_contrast", "minimalism", "geometric_precision"]],
    ["Desaturated quiet \u2014 dusty rose, muted blue, warm grey, off-white.", ["muted_palette", "warmth", "introversion"]],
    ["Saturated bold \u2014 deep navy, burnt orange, mustard, forest green.", ["maximalism", "high_contrast", "extraversion"]],
    true),

  q("s1_q05", 1, "shared", "You walk into a restaurant for the first time. What do you notice first?",
    ["The lighting.", ["cinematic_eye", "high_sensitivity"]],
    ["The music.", ["sensory_memory", "tonal_awareness"]],
    ["How the menu looks.", ["curation_instinct", "conscientiousness"]],
    ["Whether it feels like someone actually cares about the place.", ["warmth", "tactile_craft", "authenticity"]]),

  q("s1_q06", 1, "shared", "Pick the one that would hang on your wall.",
    ["A film still from a movie you love.", ["cinematic_eye", "nostalgia_pull", "sensory_memory"]],
    ["Something abstract \u2014 you can't explain why you like it, but you do.", ["gut_first", "openness"]],
    ["A photograph of a real place that means something to you.", ["warmth", "sensory_memory", "authenticity"]],
    ["Nothing. You prefer the wall clean.", ["minimalism", "curation_instinct"]]),

  q("s1_q07", 1, "shared",
    { founder: "Which typeface feels like you?", business: "Which typeface feels like the brand?" },
    ["Serif \u2014 classic, editorial, weighted.", ["analogue_texture", "premium_positioning", "formality"]],
    ["Sans-serif \u2014 clean, modern, confident.", ["minimalism", "geometric_precision", "directness"]],
    ["Handwritten \u2014 imperfect, human, personal.", ["organic_forms", "warmth_in_voice", "anti_polish"]],
    ["Monospace \u2014 technical, honest, unhidden.", ["transparency", "directness", "innovation_pull"]],
    true),

  q("s1_q08", 1, "shared", "Someone says your taste is \u201cpredictable.\u201d How does that land?",
    ["Good. Consistency is a signal, not a flaw.", ["conscientiousness", "conviction", "curation_instinct"]],
    ["Fine. You know what you like. That's not a weakness.", ["thick_skin", "taste_as_identity"]],
    ["Badly. You'd rather be surprising than safe.", ["risk_appetite", "innovation_pull", "openness"]],
    ["You'd wonder what they think they know about you.", ["independence", "introversion"]]),

  q("s1_q09", 1, "shared",
    { founder: "You're hosting. What's the music?", business: "The brand is hosting an event. What's the music?" },
    ["Low, warm, ambient. People don't notice it \u2014 they just feel better.", ["warmth", "introversion", "muted_palette"]],
    ["Something with personality. A deliberate choice that says something about the host.", ["taste_as_identity", "curation_instinct", "extraversion"]],
    ["Silence. Let the conversation fill the room.", ["minimalism", "admires_restraint", "quiet_confidence"]],
    ["Something slightly unexpected. Not what they'd pick \u2014 but they'll remember it.", ["innovation_pull", "underdog_energy", "anti_polish"]]),

  q("s1_q10", 1, "shared", "When does a space feel \u201cdone\u201d to you?",
    ["When there's nothing left to remove.", ["minimalism", "curation_instinct", "admires_restraint"]],
    ["When it feels warm. You can't rush that \u2014 it takes time and real things.", ["warmth", "patience", "tactile_craft"]],
    ["When it has a point of view. Not decorated \u2014 directed.", ["cinematic_eye", "conviction", "taste_as_identity"]],
    ["It's never done. That's the point.", ["pragmatism", "openness", "improviser"]]),

  q("s1_q11", 1, "shared", "Which decade's visual culture do you find yourself drawn to?",
    ["The 1970s \u2014 warm, textured, unpolished, human.", ["analogue_texture", "warmth", "nostalgia_pull", "organic_forms"]],
    ["The 1990s \u2014 raw, unfinished, anti-glamour.", ["anti_polish", "nostalgia_pull", "underdog_energy"]],
    ["The 2020s \u2014 clean, considered, intentional.", ["minimalism", "innovation_pull", "geometric_precision"]],
    ["None. You take pieces from everywhere and make something new.", ["genre_fluency", "curation_instinct", "openness"]],
    true),

  q("s1_q12", 1, "shared", "A designer shows you two logos. One is polished and geometric. The other is rough and hand-drawn. Neither is for your brand. Which do you respect more?",
    ["The polished one. Precision takes discipline.", ["geometric_precision", "conscientiousness", "admires_craft"]],
    ["The rough one. It has life in it.", ["organic_forms", "anti_polish", "emotional_resonance"]],
    ["Whichever one does a better job of saying something real.", ["authenticity", "pragmatism"]],
    ["You notice what each one chose to leave out.", ["curation_instinct", "admires_restraint", "intellectual_depth"]]),

  q("s1_q13", 1, "shared", "What makes you trust a brand before you've bought anything?",
    ["They don't try too hard. There's a quiet confidence in how they present.", ["quiet_confidence", "premium_positioning"]],
    ["Everything looks considered \u2014 like someone who gives a damn is behind it.", ["tactile_craft", "conscientiousness", "admires_craft"]],
    ["They feel like a real person, not a marketing department.", ["warmth_in_voice", "authenticity", "personality_forward"]],
    ["They show their work. Process, not just output.", ["transparency", "storytelling"]]),

  q("s1_q14", 1, "founder", "Think about the object you've kept the longest. Why have you kept it?",
    ["It reminds you of a specific moment or person.", ["sensory_memory", "loyalty", "warmth"]],
    ["It's genuinely well made. That kind of quality doesn't happen anymore.", ["tactile_craft", "admires_craft", "nostalgia_pull"]],
    ["Honestly, you don't know. But throwing it out feels wrong.", ["gut_first", "high_sensitivity", "loyalty"]],
    ["It still works. That's enough.", ["pragmatism", "conscientiousness"]]),

  q("s1_q15", 1, "shared", "You're scrolling and you stop on something. What made you stop?",
    ["A photograph with incredible light.", ["cinematic_eye", "high_contrast"]],
    ["A texture you can almost feel through the screen.", ["tactile_craft", "sensory_memory"]],
    ["Something visually unexpected \u2014 it broke a pattern.", ["innovation_pull", "risk_appetite", "openness"]],
    ["A composition so clean it made you exhale.", ["minimalism", "geometric_precision", "admires_restraint"]]),

  q("s1_q16", 1, "shared",
    { founder: "Which of these image treatments feels most like you?", business: "Which of these image treatments feels most like the brand?" },
    ["Film grain, warm colour cast, slightly overexposed.", ["analogue_texture", "warmth", "nostalgia_pull"]],
    ["High contrast black and white, deep shadows.", ["high_contrast", "cinematic_eye", "minimalism"]],
    ["Soft focus, muted tones, dreamy.", ["muted_palette", "organic_forms", "introversion"]],
    ["Sharp, saturated, modern editorial.", ["geometric_precision", "high_contrast", "innovation_pull"]],
    true),

  q("s1_q17", 1, "shared",
    { founder: "What would you never wear \u2014 visually speaking?", business: "What would the brand never wear \u2014 visually speaking?" },
    ["Anything that looks like everyone else's.", ["curation_instinct", "independence", "rejects_trend"]],
    ["Anything loud for the sake of being loud.", ["admires_restraint", "quiet_confidence", "prudence"]],
    ["Anything overly polished or corporate.", ["anti_polish", "authenticity", "warmth"]],
    ["Anything dated. You respect the past, but you don't live there.", ["innovation_pull", "pragmatism"]]),

  q("s1_q18", 1, "business", "Your brand has a visual signature \u2014 the thing people recognise before they see the name. What is it?",
    ["Consistency. Same colours, same structure, every time.", ["geometric_precision", "conscientiousness", "curation_instinct"]],
    ["Warmth. Even at a glance, it feels human and approachable.", ["warmth", "personality_forward"]],
    ["Edge. There's always something slightly unexpected in the frame.", ["anti_polish", "innovation_pull", "admires_boldness"]],
    ["Restraint. What's absent is as intentional as what's present.", ["minimalism", "admires_restraint", "quiet_confidence"]]),

  q("s1_q19", 1, "business", "A potential customer sees one piece of your visual identity before anything else. What would make them leave?",
    ["If it looked cheap. Quality is the first signal.", ["premium_positioning", "admires_craft", "tactile_craft"]],
    ["If it felt cold. No warmth, no sign of a real person behind it.", ["warmth", "personality_forward", "warmth_in_voice"]],
    ["If it looked like everything else in the category.", ["curation_instinct", "rejects_trend", "category_creation"]],
    ["If it was trying too hard. Desperation is visible.", ["quiet_confidence", "admires_restraint"]]),
];
