import type { BasSummary, PandLSummary, ExportPeriod } from "./export-queries";

function moneyAud(value: number): string {
  const abs = Math.abs(value);
  const formatted = abs.toLocaleString("en-AU", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return value < 0 ? `-$${formatted}` : `$${formatted}`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const baseStyles = `
  body {
    font-family: Georgia, 'Times New Roman', serif;
    color: #1a1a1a;
    background: #faf5ef;
    margin: 0;
    padding: 40px;
    line-height: 1.6;
  }
  h1 { font-size: 28px; margin: 0 0 4px 0; letter-spacing: -0.5px; }
  h2 { font-size: 18px; margin: 32px 0 12px 0; letter-spacing: -0.3px; }
  .subtitle { color: #666; font-size: 13px; margin: 0 0 32px 0; }
  .brand { color: #c03e2c; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0 24px 0; }
  th { text-align: left; font-size: 11px; text-transform: uppercase;
       letter-spacing: 1px; color: #666; padding: 8px 12px;
       border-bottom: 2px solid #1a1a1a; }
  td { padding: 8px 12px; border-bottom: 1px solid #e0dbd4; font-size: 14px; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; }
  th.num { text-align: right; }
  .total-row td { font-weight: 700; border-top: 2px solid #1a1a1a; border-bottom: none; }
  .footer { margin-top: 40px; font-size: 11px; color: #999;
            border-top: 1px solid #e0dbd4; padding-top: 12px; }
`;

export function buildBasPdfHtml(summary: BasSummary): string {
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>BAS Summary — ${escapeHtml(summary.period.label)}</title>
<style>${baseStyles}</style>
</head><body>
<h1>BAS Summary</h1>
<p class="subtitle">${escapeHtml(summary.period.label)} &mdash; ${escapeHtml(summary.period.start)} to ${escapeHtml(summary.period.end)}<br>
<span class="brand">SuperBad Media</span> &middot; Generated ${new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" })}</p>

<h2>GST Summary</h2>
<table>
  <tr><th>Item</th><th class="num">Amount (AUD)</th></tr>
  <tr><td>GST collected on sales</td><td class="num">${moneyAud(summary.gst_collected_inc)}</td></tr>
  <tr><td>GST paid on purchases</td><td class="num">${moneyAud(summary.gst_paid_on_expenses)}</td></tr>
  <tr class="total-row"><td>Net GST payable</td><td class="num">${moneyAud(summary.net_gst_payable)}</td></tr>
</table>

<h2>Revenue &amp; Expenses</h2>
<table>
  <tr><th>Item</th><th class="num">Inc. GST</th><th class="num">Ex. GST</th></tr>
  <tr><td>Total revenue</td><td class="num">${moneyAud(summary.total_revenue_inc)}</td><td class="num">${moneyAud(summary.total_revenue_ex)}</td></tr>
  <tr><td>Total expenses</td><td class="num">${moneyAud(summary.total_expenses_inc)}</td><td class="num">${moneyAud(summary.total_expenses_ex)}</td></tr>
  <tr class="total-row"><td>Net</td><td class="num">${moneyAud(summary.total_revenue_inc - summary.total_expenses_inc)}</td><td class="num">${moneyAud(summary.total_revenue_ex - summary.total_expenses_ex)}</td></tr>
</table>

<div class="footer">
  This is a summary for accountant reference only. It is not a lodged BAS.<br>
  SuperBad Media &middot; ABN to be confirmed &middot; Generated by SuperBad
</div>
</body></html>`;
}

export function buildPandLPdfHtml(summary: PandLSummary): string {
  const breakdownRows = summary.expense_breakdown
    .map(
      (r) =>
        `<tr><td style="padding-left:24px">${escapeHtml(r.label)}</td><td class="num">${moneyAud(r.total_inc_gst)}</td><td class="num">${moneyAud(r.total_ex_gst)}</td></tr>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Profit &amp; Loss — ${escapeHtml(summary.period.label)}</title>
<style>${baseStyles}</style>
</head><body>
<h1>Profit &amp; Loss</h1>
<p class="subtitle">${escapeHtml(summary.period.label)} &mdash; ${escapeHtml(summary.period.start)} to ${escapeHtml(summary.period.end)}<br>
<span class="brand">SuperBad Media</span> &middot; Generated ${new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" })}</p>

<table>
  <tr><th>Item</th><th class="num">Inc. GST</th><th class="num">Ex. GST</th></tr>
  <tr><td><strong>Revenue</strong></td><td class="num">${moneyAud(summary.revenue_inc_gst)}</td><td class="num">${moneyAud(summary.revenue_ex_gst)}</td></tr>
  <tr><td><strong>Expenses</strong></td><td class="num">${moneyAud(summary.expenses_inc_gst)}</td><td class="num">${moneyAud(summary.expenses_ex_gst)}</td></tr>
  ${breakdownRows}
  <tr class="total-row"><td>Net profit</td><td class="num">${moneyAud(summary.net_profit_inc_gst)}</td><td class="num">${moneyAud(summary.net_profit_ex_gst)}</td></tr>
</table>

<div class="footer">
  This is an estimate for reference only. Consult your accountant for tax purposes.<br>
  SuperBad Media &middot; ABN to be confirmed &middot; Generated by SuperBad
</div>
</body></html>`;
}

export function exportFilename(periodLabel: string): string {
  const slug = periodLabel
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  const dateStr = new Date().toISOString().split("T")[0];
  return `superbad-finance-${slug}-${dateStr}`;
}
