import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";
import { companies } from "./companies";
import { contacts } from "./contacts";
import { deals } from "./deals";

/**
 * Cross-spec audit log. The consolidated `kind` union lives here as the
 * single source of truth — every spec that emits activity events adds its
 * block below. Lifted from `docs/specs/sales-pipeline.md` §4.1 (Phase 3.5
 * step 2a consolidation, 2026-04-13) plus post-step-2a additions.
 *
 * FK refs on `company_id` (cascade), `contact_id` (set null), and
 * `deal_id` (cascade) wired in SP-1 once the upstream tables landed.
 */
export const ACTIVITY_LOG_KINDS = [
  // --- Sales Pipeline (original, 11) ---
  "note",
  "stage_change",
  "email_sent",
  "email_received",
  "email_bounced",
  "email_complained",
  "quote_sent",
  "payment_received",
  "trial_shoot_booked",
  "trial_shoot_completed",
  "feedback_received",
  // --- Cost & Usage Observatory (10) ---
  "cost_anomaly_fired",
  "cost_anomaly_acknowledged",
  "cost_anomaly_resolved",
  "kill_switch_triggered",
  "kill_switch_released",
  "band_adjusted",
  "monthly_threshold_crossed",
  "projection_threshold_crossed",
  "cost_attribution_transferred",
  "observatory_settings_changed",
  // --- Finance Dashboard (8) ---
  "finance_expense_created",
  "finance_expense_updated",
  "finance_expense_confirmed",
  "finance_recurring_booked",
  "finance_recurring_created",
  "finance_recurring_paused",
  "finance_export_generated",
  "finance_bas_filed",
  // --- Hiring Pipeline (16) ---
  "candidate_sourced",
  "candidate_invited",
  "candidate_applied",
  "candidate_followup_received",
  "candidate_screened",
  "candidate_trial_sent",
  "candidate_trial_delivered",
  "candidate_trial_reviewed",
  "candidate_benched",
  "candidate_paused",
  "candidate_resumed",
  "candidate_archived",
  "candidate_unarchived",
  "role_brief_opened",
  "role_brief_regenerated",
  "role_brief_closed",
  // --- Client Context Engine — active_strategy (4) ---
  "active_strategy_created",
  "active_strategy_reviewed",
  "active_strategy_updated",
  "active_strategy_archived",
  // --- Quote Builder (17) ---
  "quote_draft_started",
  "quote_viewed",
  "quote_accepted",
  "quote_settled",
  "quote_superseded",
  "quote_expired",
  "quote_reminder_sent",
  "quote_withdrawn",
  "scheduled_task_dispatched",
  "subscription_cancel_intercepted_preterm",
  "subscription_early_cancel_paid_remainder",
  "subscription_early_cancel_buyout_50pct",
  "subscription_paused",
  "subscription_pause_ended",
  "subscription_upgrade_intent",
  "subscription_downgrade_intent",
  "subscription_cancelled_post_term",
  "subscription_ended_gracefully",
  // --- Branded Invoicing (8) ---
  "invoice_generated",
  "invoice_sent",
  "invoice_overdue",
  "invoice_reminder_sent",
  "invoice_marked_paid",
  "invoice_paid_online",
  "invoice_superseded",
  "invoice_voided",
  // --- Brand DNA Assessment (8) ---
  "assessment_started",
  "section_completed",
  "assessment_completed",
  "profile_generated",
  "blend_generated",
  "invite_created",
  "invite_used",
  "retake_started",
  // --- Intro Funnel (21) ---
  "intro_funnel_started",
  "intro_funnel_section_completed",
  "intro_funnel_abandoned",
  "intro_funnel_paid",
  "intro_funnel_sms_sent",
  "intro_funnel_sms_delivered",
  "intro_funnel_sms_replied",
  "intro_funnel_cancelled_refunded",
  "intro_funnel_cancelled_no_refund",
  "intro_funnel_no_show",
  "shoot_booked",
  "shoot_rescheduled",
  "shoot_cancelled",
  "shoot_cancelled_by_superbad",
  "shoot_rescheduled_by_superbad",
  "shoot_reschedule_limit_hit",
  "deliverables_ready",
  "deliverables_viewed",
  "post_trial_negative_feedback",
  "retainer_fit_recommendation_ready",
  "reflection_complete",
  // --- Lead Generation (10) ---
  "outreach_sent",
  "outreach_opened",
  "outreach_clicked",
  "outreach_replied",
  "outreach_bounced",
  "outreach_unsubscribed",
  "sequence_stopped_engagement",
  "sequence_stopped_manual",
  "autonomy_graduated",
  "autonomy_demoted",
  // --- Content Engine (15) ---
  "content_topic_researched",
  "content_topic_vetoed",
  "content_draft_generated",
  "content_draft_approved",
  "content_draft_rejected",
  "content_post_published",
  "content_newsletter_scheduled",
  "content_newsletter_sent",
  "content_social_draft_generated",
  "content_social_published",
  "content_subscriber_added",
  "content_subscriber_removed",
  "content_outreach_matched",
  "content_seed_keyword_added",
  "content_seed_keyword_removed",
  // --- Client Context Engine — non-active_strategy (11) ---
  "context_summary_regenerated",
  "action_item_extracted",
  "action_item_manual_created",
  "action_item_completed",
  "action_item_dismissed",
  "action_item_edited",
  "draft_generated",
  "draft_nudged",
  "draft_sent",
  "draft_discarded",
  "draft_channel_switched",
  // --- Client Management (8) ---
  "portal_chat_message_sent",
  "portal_chat_escalated",
  "portal_chat_action_taken",
  "data_export_requested",
  "data_export_completed",
  "external_link_added",
  "external_link_removed",
  "client_profile_viewed_by_admin",
  // --- Daily Cockpit (8) ---
  "cockpit_brief_generated",
  "cockpit_brief_regenerated",
  "cockpit_brief_skipped_quiet",
  "cockpit_waiting_opened",
  "cockpit_health_opened",
  "cockpit_chip_tapped",
  "cockpit_banner_dismissed",
  "cockpit_slot_rolled_over",
  // --- Onboarding + Segmentation (8) ---
  "onboarding_started",
  "onboarding_welcome_email_sent",
  "onboarding_brand_dna_started",
  "onboarding_brand_dna_completed",
  "onboarding_revenue_seg_completed",
  "onboarding_product_config_completed",
  "onboarding_practical_setup_step_completed",
  "onboarding_credentials_created",
  "onboarding_completed",
  // --- SaaS Subscription Billing (11) ---
  "saas_product_created",
  "saas_product_published",
  "saas_product_archived",
  "saas_subscription_created",
  "saas_subscription_upgraded",
  "saas_subscription_downgraded",
  "saas_subscription_product_switched",
  "saas_payment_failed_lockout",
  "saas_payment_recovered",
  "saas_data_loss_warning_sent",
  "saas_usage_limit_reached",
  "saas_usage_period_rollover",
  "saas_tier_downgrade_scheduled",
  // --- SaaS cancel flow (SB-11) ---
  // Unified terminal-cancel kind for SaaS. Emitted on all three SaaS
  // terminal transitions (`cancelled_paid_remainder`, `cancelled_buyout`,
  // `cancelled_post_term`) alongside the existing retainer-flavoured
  // `subscription_early_cancel_*` / `subscription_cancelled_post_term`
  // kinds. Carries `meta.branch` so downstream consumers (churn signals,
  // retention reporting) can slice by exit path without pattern-matching
  // against three separate kinds. Closes `sb10_churn_precision_upgrade`.
  "saas_subscription_cancelled",
  // --- Setup Wizards (6) ---
  "wizard_started",
  "wizard_step_completed",
  "wizard_completed",
  "wizard_abandoned",
  "wizard_resumed",
  "integration_registered",
  // --- Unified Inbox (19) ---
  "inbox_thread_created",
  "inbox_message_received",
  "inbox_message_sent",
  "inbox_routed",
  "inbox_routed_reviewed",
  "inbox_notification_fired",
  "inbox_notification_corrected",
  "inbox_draft_generated",
  "inbox_draft_composed",
  "inbox_draft_refined",
  "inbox_draft_sent",
  "inbox_draft_discarded",
  "inbox_hygiene_purged",
  "inbox_noise_promoted",
  "inbox_keep_pinned",
  "inbox_import_completed",
  "inbox_import_backfilled",
  "inbox_ticket_status_changed",
  "inbox_ticket_type_assigned",
  "inbox_ticket_type_changed",
  "inbox_ticket_resolved",
  "inbox_ticket_auto_resolved",
  "inbox_calendar_rsvp_sent",
  "inbox_attachment_uploaded",
  "inbox_thread_merged",
  // --- Six-Week Plan Generator (17) ---
  "six_week_plan_generation_started",
  "six_week_plan_strategy_ready_for_review",
  "six_week_plan_strategy_approved",
  "six_week_plan_strategy_regenerated",
  "six_week_plan_detail_ready_for_review",
  "six_week_plan_approved",
  "six_week_plan_released",
  "six_week_plan_self_activated",
  "six_week_plan_revision_requested",
  "six_week_plan_revision_regenerated",
  "six_week_plan_revision_explained",
  "six_week_plan_superseded_by_revision",
  "six_week_plan_migrated_to_client_context",
  "six_week_plan_refresh_review_requested",
  "six_week_plan_live_strategy_set",
  "six_week_plan_portal_archived_non_converter",
  "six_week_plan_pdf_downloaded",
  // --- Shape canonicalisation (2) ---
  "company_shape_updated",
  "shape_mismatch_flagged",
  // --- Email adapter A7 (3) ---
  "drift_check_failed",
  "portal_magic_link_sent",
  "portal_magic_link_redeemed",
  // --- Portal guard A8 (1) ---
  "portal_session_started",
  // --- Support + error triage B1 (1) ---
  "support_ticket_created",
  // --- Brand DNA invite flow BDA-1 (2) ---
  "brand_dna_invite_sent",
  "brand_dna_invite_redeemed",
] as const;

export type ActivityLogKind = (typeof ACTIVITY_LOG_KINDS)[number];

export const activity_log = sqliteTable(
  "activity_log",
  {
    id: text("id").primaryKey(),
    company_id: text("company_id").references(() => companies.id, {
      onDelete: "cascade",
    }),
    contact_id: text("contact_id").references(() => contacts.id, {
      onDelete: "set null",
    }),
    deal_id: text("deal_id").references(() => deals.id, {
      onDelete: "cascade",
    }),
    kind: text("kind", { enum: ACTIVITY_LOG_KINDS }).notNull(),
    body: text("body").notNull(),
    meta: text("meta", { mode: "json" }),
    created_at_ms: integer("created_at_ms").notNull(),
    created_by: text("created_by"),
  },
  (t) => ({
    by_company: index("activity_log_company_idx").on(t.company_id, t.created_at_ms),
    by_contact: index("activity_log_contact_idx").on(t.contact_id, t.created_at_ms),
    by_deal: index("activity_log_deal_idx").on(t.deal_id, t.created_at_ms),
    by_kind: index("activity_log_kind_idx").on(t.kind, t.created_at_ms),
  }),
);

export type ActivityLogRow = typeof activity_log.$inferSelect;
export type ActivityLogInsert = typeof activity_log.$inferInsert;
