import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

/**
 * Company-level Brand DNA blend — synthesised from ≥2 individual profiles.
 *
 * Generated by Opus when a company reaches ≥2 completed `brand_dna_profiles`
 * rows. Captures shared signals, explicit divergences, and a composite
 * narrative. Regenerated whenever any stakeholder retakes their assessment.
 *
 * Downstream prompt injection:
 *   - One-to-one comms → individual profile
 *   - Company-wide work (proposals, brand content) → blend (if exists)
 *
 * Owner: BDA-1. Consumer: BDA-3 (blend generation), downstream LLM callers.
 */
export const brand_dna_blends = sqliteTable(
  "brand_dna_blends",
  {
    id: text("id").primaryKey(),
    /** FK to companies.id — the company this blend represents. */
    company_id: text("company_id").notNull(),
    /**
     * JSON array of individual brand_dna_profiles.id values that were
     * blended. Used to detect staleness when a stakeholder retakes.
     * E.g. ["bda_profile_001", "bda_profile_002"].
     */
    source_profile_ids: text("source_profile_ids").notNull(),
    /**
     * Blended domain → tag → frequency map (same shape as
     * brand_dna_profiles.signal_tags). Shared signals amplified;
     * divergent signals reduced proportionally.
     */
    tags_json: text("tags_json").notNull(),
    /** Blended prose portrait — Opus-generated synthesis narrative. */
    prose_portrait: text("prose_portrait").notNull(),
    /**
     * Structured divergence flags — JSON array of objects describing where
     * stakeholders disagree. E.g. [{ domain: "communication", tag: "directness",
     * stakeholder_a: 6, stakeholder_b: 1, interpretation: "..." }].
     * These are surfaced explicitly in the reveal rather than averaged away.
     */
    divergences_json: text("divergences_json").notNull(),
    /** UTC epoch ms when this blend was generated. */
    created_at_ms: integer("created_at_ms").notNull(),
  },
  (t) => ({
    by_company: index("brand_dna_blends_company_idx").on(
      t.company_id,
      t.created_at_ms,
    ),
  }),
);

export type BrandDnaBlendRow = typeof brand_dna_blends.$inferSelect;
export type BrandDnaBlendInsert = typeof brand_dna_blends.$inferInsert;
