INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('sms.quiet_window_start_hour', '8', 'integer', 'SMS quiet window start (local hour, inclusive)', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('sms.quiet_window_end_hour', '21', 'integer', 'SMS quiet window end (local hour, exclusive)', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('inbox.noise_retention_days_transactional', '180', 'integer', 'Days to keep noise/transactional messages before soft-delete', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('inbox.noise_retention_days_default', '30', 'integer', 'Days to keep noise (non-transactional) messages before soft-delete', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('inbox.spam_retention_days', '7', 'integer', 'Days to keep spam messages before soft-delete', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('inbox.trash_retention_days', '14', 'integer', 'Days soft-deleted messages survive before hard-delete', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('tasks.approval_reminder_hours', '48', 'integer', 'Hours before a reminder fires for unanswered approval requests', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('wizards.expiry_warn_hours_before', '24', 'integer', 'Hours before wizard expiry to fire the warning notification', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('surprise.per_egg_cooldown_days', '30', 'integer', 'Per-trigger cooldown (days) for individual admin eggs', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('surprise.milestone_cooldown_days', '60', 'integer', 'Per-contact cooldown (days) for milestone-spotter egg', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('surprise.fire_retention_days', '30', 'integer', 'Days to retain hidden_egg_fires rows before cleanup', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('hiring.trial.auto_archive_delay_days', '2', 'integer', 'Days after trial overdue before auto-archive', 0);--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`, `type`, `description`, `updated_at_ms`) VALUES ('observatory.anomaly_suppress_hours', '24', 'integer', 'Hours an acknowledged anomaly stays suppressed', 0);
