/**
 * Public blog post route — `/blog/[slug]`.
 *
 * Multi-tenant: resolves the owning company from the request hostname
 * via `companies.domain`. Falls back to the NEXT_PUBLIC_APP_URL host
 * for SuperBad's own blog at `superbadmedia.com.au/blog/*`.
 *
 * SEO package: title tag, meta description, OG image, JSON-LD Article
 * schema, canonical URL, table of contents (inline in markdown body).
 *
 * Owner: CE-3.
 */
import { notFound } from "next/navigation";
import { headers } from "next/headers";
import type { Metadata } from "next";
import { getPublishedPost, resolveCompanyByDomain } from "@/lib/content-engine/publish";

interface BlogPageProps {
  params: Promise<{ slug: string }>;
}

/** Resolve the company ID from the request hostname. */
async function resolveCompanyId(): Promise<string | null> {
  const headerStore = await headers();
  const host =
    headerStore.get("x-forwarded-host") ??
    headerStore.get("host") ??
    "";

  // Try to match the hostname to a company
  const company = await resolveCompanyByDomain(host);
  if (company) return company.id;

  // Fallback: check if this is the main SuperBad domain
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "";
  const appHost = appUrl.replace(/^https?:\/\//, "").replace(/\/.*$/, "");
  if (host.replace(/:\d+$/, "") === appHost.replace(/:\d+$/, "")) {
    // SuperBad's own blog — find the SuperBad company
    const sbCompany = await resolveCompanyByDomain(appHost);
    return sbCompany?.id ?? null;
  }

  return null;
}

export async function generateMetadata({
  params,
}: BlogPageProps): Promise<Metadata> {
  const { slug } = await params;
  const companyId = await resolveCompanyId();
  if (!companyId) return { title: "Not Found" };

  const post = await getPublishedPost(companyId, slug);
  if (!post) return { title: "Not Found" };

  const structuredData = post.structured_data as Record<string, unknown> | null;

  return {
    title: post.title,
    description: post.meta_description ?? undefined,
    openGraph: {
      title: post.title,
      description: post.meta_description ?? undefined,
      url: post.published_url ?? undefined,
      type: "article",
      ...(post.og_image_url ? { images: [{ url: post.og_image_url }] } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.meta_description ?? undefined,
      ...(post.og_image_url ? { images: [post.og_image_url] } : {}),
    },
    alternates: {
      canonical: post.published_url ?? undefined,
    },
    other: structuredData
      ? { "script:ld+json": JSON.stringify(structuredData) }
      : undefined,
  };
}

export default async function BlogPostPage({ params }: BlogPageProps) {
  const { slug } = await params;
  const companyId = await resolveCompanyId();
  if (!companyId) notFound();

  const post = await getPublishedPost(companyId, slug);
  if (!post) notFound();

  const structuredData = post.structured_data as Record<string, unknown> | null;

  return (
    <>
      {/* JSON-LD structured data */}
      {structuredData && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
      )}

      <article className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        <header className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
            {post.title}
          </h1>
          {post.published_at_ms && (
            <time
              dateTime={new Date(post.published_at_ms).toISOString()}
              className="mt-2 block text-sm text-muted-foreground"
            >
              {new Date(post.published_at_ms).toLocaleDateString("en-AU", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </time>
          )}
        </header>

        {/* Markdown body rendered as HTML via dangerouslySetInnerHTML.
            The body is generated by Opus and drift-checked — not user-submitted.
            A markdown→HTML renderer (e.g. remark) is a CE-5+ enhancement;
            for now, render the raw markdown as pre-formatted prose. */}
        <div className="prose prose-neutral max-w-none dark:prose-invert">
          <MarkdownRenderer body={post.body} />
        </div>

        {/* Newsletter opt-in CTA — spec §2.1 Stage 5 */}
        <aside className="mt-16 rounded-lg border border-border bg-surface-1 p-6 text-center">
          <p className="text-sm text-muted-foreground">
            Want more like this? Subscribe to get new posts straight to your inbox.
          </p>
          <p className="mt-2 text-xs text-muted-foreground">
            No spam. Unsubscribe anytime.
          </p>
        </aside>
      </article>
    </>
  );
}

/**
 * Simple markdown-to-HTML renderer. Handles headings, paragraphs, bold,
 * italic, links, lists, and code blocks. A proper remark/rehype pipeline
 * is a CE-5+ enhancement.
 */
function MarkdownRenderer({ body }: { body: string }) {
  const html = markdownToHtml(body);
  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}

function markdownToHtml(md: string): string {
  let html = md
    // Code blocks (must come before inline code)
    .replace(
      /```(\w*)\n([\s\S]*?)```/g,
      (_m, lang: string, code: string) =>
        `<pre><code class="language-${lang}">${escapeHtml(code.trim())}</code></pre>`,
    )
    // Inline code
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    // Headings
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    // Bold + italic
    .replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // Links
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    // Unordered lists
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    // Horizontal rules
    .replace(/^---$/gm, "<hr />")
    // Paragraphs (blank-line separated)
    .replace(/\n\n/g, "</p><p>");

  // Wrap loose list items
  html = html.replace(/(<li>[\s\S]*?<\/li>)/g, "<ul>$1</ul>");
  // Clean up duplicate ul wrappers
  html = html.replace(/<\/ul>\s*<ul>/g, "");

  // Wrap in paragraph tags if not already
  if (!html.startsWith("<")) {
    html = `<p>${html}</p>`;
  }

  return html;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
